apiVersion: v1
kind: Service 
metadata: 
  name: sample-svc 
spec: 
  selector: 
    run: sample-app
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: <リージョン名>/<テナント名>/<リポジトリ名>/sample-app
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: <シークレット名>
