apiVersion: v1
kind: Service 
metadata: 
  name: sample-app-svc 
spec: 
  type: LoadBalancer
  selector: 
    app: sample-app
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: iad.ocir.io/pmcbc/test-repo/sample-app:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: test-secret
